import type { Metadata } from "next";
import "./globals.css";
import "antd/dist/reset.css"; // antd 리셋 css

import Layout from "@/components/layout/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased min-h-screen bg-background text-foreground">
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
